// THIS IS THE PROVIDED CODE FOR PROGRAM #2, DSA 1, SPRING 2021

#include <iostream>
#include <fstream>
#include <sstream>
#include <list>
#include <vector>
#include <string>
#include <algorithm>
#include <ctime>
#include <cmath>
#include <cstring>
#include <cctype>
#include <cstdlib>

using namespace std;

// A simple class; each object holds four public fields
class Data {
public:
    string lastName;
    string firstName;
    string ssn;
};

// Load the data from a specified input file
void loadDataList(list<Data *> &l, const string &filename) {

    ifstream input(filename);
    if (!input) {
        cerr << "Error: could not open " << filename << "\n";
        exit(1);
    }

    // The first line indicates the size
    string line;
    getline(input, line);
    stringstream ss(line);
    int size;
    ss >> size;

    // Load the data
    for (int i = 0; i < size; i++) {
        getline(input, line);
        stringstream ss2(line);
        Data *pData = new Data();
        ss2 >> pData->lastName >> pData->firstName >> pData->ssn;
        l.push_back(pData);
    }

    input.close();
}

// Output the data to a specified output file
void writeDataList(const list<Data *> &l, const string &filename) {

    ofstream output(filename);
    if (!output) {
        cerr << "Error: could not open " << filename << "\n";
        exit(1);
    }

    // Write the size first
    int size = l.size();
    output << size << "\n";

    // Write the data
    for (auto pData:l) {
        output << pData->lastName << " "
               << pData->firstName << " "
               << pData->ssn << "\n";
    }

    output.close();
}

// Sort the data according to a specified field
// (Implementation of this function will be later in this file)
void sortDataList(list<Data *> &);

// The main function calls routines to get the data, sort the data,
// and output the data. The sort is timed according to CPU time.
int main() {
    string filename;
    cout << "Enter name of input file: ";
    cin >> filename;
    list<Data *> theList;
    loadDataList(theList, filename);

    cout << "Data loaded.\n";

    cout << "Executing sort...\n";
    clock_t t1 = clock();
    sortDataList(theList);
    clock_t t2 = clock();
    double timeDiff = ((double) (t2 - t1)) / CLOCKS_PER_SEC;

    cout << "Sort finished. CPU time was " << timeDiff << " seconds.\n";

    cout << "Enter name of output file: ";
    cin >> filename;
    writeDataList(theList, filename);

    return 0;
}

// -------------------------------------------------
// YOU MAY NOT CHANGE OR ADD ANY CODE ABOVE HERE !!!
// -------------------------------------------------

// You may add global variables, functions, and/or
// class defintions here if you wish.

#include <unordered_map>
#include <iterator>


unordered_map<string, int> last_names = //equated names with increasing numerical values based on alphabetical order
        {
                {"ACOSTA",1},
                {"ADAMS",2},
                {"ADKINS",3},
                {"AGUILAR",4},
                {"AGUIRRE",5},
                {"ALEXANDER",6},
                {"ALLEN",7},
                {"ALVARADO",8},
                {"ALVAREZ",9},
                {"ANDERSON",10},
                {"ANDREWS",11},
                {"ARMSTRONG",12},
                {"ARNOLD",13},
                {"AUSTIN",14},
                {"AVILA",15},
                {"AYALA",16},
                {"BAILEY",17},
                {"BAKER",18},
                {"BALDWIN",19},
                {"BANKS",20},
                {"BARBER",21},
                {"BARKER",22},
                {"BARNES",23},
                {"BARNETT",24},
                {"BARRETT",25},
                {"BARTON",26},
                {"BATES",27},
                {"BECK",28},
                {"BECKER",29},
                {"BELL",30},
                {"BENNETT",31},
                {"BENSON",32},
                {"BERRY",33},
                {"BISHOP",34},
                {"BLACK",35},
                {"BLAIR",36},
                {"BLAKE",37},
                {"BOWEN",38},
                {"BOWMAN",39},
                {"BOYD",40},
                {"BRADLEY",41},
                {"BRADY",42},
                {"BREWER",43},
                {"BROOKS",44},
                {"BROWN",45},
                {"BRYANT",46},
                {"BURGESS",47},
                {"BURKE",48},
                {"BURNS",49},
                {"BURTON",50},
                {"BUSH",51},
                {"BUTLER",52},
                {"BYRD",53},
                {"CABRERA",54},
                {"CALDERON",55},
                {"CALDWELL",56},
                {"CAMACHO",57},
                {"CAMPBELL",58},
                {"CAMPOS",59},
                {"CANNON",60},
                {"CARDENAS",61},
                {"CARLSON",62},
                {"CARPENTER",63},
                {"CARR",64},
                {"CARRILLO",65},
                {"CARROLL",66},
                {"CARTER",67},
                {"CASTANEDA",68},
                {"CASTILLO",69},
                {"CASTRO",70},
                {"CERVANTES",71},
                {"CHAMBERS",72},
                {"CHAN",73},
                {"CHANDLER",74},
                {"CHANG",75},
                {"CHAPMAN",76},
                {"CHAVEZ",77},
                {"CHEN",78},
                {"CHRISTENSEN",79},
                {"CLARK",80},
                {"CLARKE",81},
                {"COHEN",82},
                {"COLE",83},
                {"COLEMAN",84},
                {"COLLINS",85},
                {"COLON",86},
                {"CONTRERAS",87},
                {"COOK",88},
                {"COOPER",89},
                {"CORTEZ",90},
                {"COX",91},
                {"CRAIG",92},
                {"CRAWFORD",93},
                {"CROSS",94},
                {"CRUZ",95},
                {"CUMMINGS",96},
                {"CUNNINGHAM",97},
                {"CURRY",98},
                {"CURTIS",99},
                {"DANIEL",100},
                {"DANIELS",101},
                {"DAVIDSON",102},
                {"DAVIS",103},
                {"DAWSON",104},
                {"DAY",105},
                {"DEAN",106},
                {"DELACRUZ",107},
                {"DELEON",108},
                {"DELGADO",109},
                {"DENNIS",110},
                {"DIAZ",111},
                {"DIXON",112},
                {"DOMINGUEZ",113},
                {"DOUGLAS",114},
                {"DOYLE",115},
                {"DUNCAN",116},
                {"DUNN",117},
                {"DURAN",118},
                {"EDWARDS",119},
                {"ELLIOTT",120},
                {"ELLIS",121},
                {"ERICKSON",122},
                {"ESPINOZA",123},
                {"ESTRADA",124},
                {"EVANS",125},
                {"FARMER",126},
                {"FERGUSON",127},
                {"FERNANDEZ",128},
                {"FIELDS",129},
                {"FIGUEROA",130},
                {"FISCHER",131},
                {"FISHER",132},
                {"FITZGERALD",133},
                {"FLEMING",134},
                {"FLETCHER",135},
                {"FLORES",136},
                {"FORD",137},
                {"FOSTER",138},
                {"FOWLER",139},
                {"FOX",140},
                {"FRANCIS",141},
                {"FRANCO",142},
                {"FRANK",143},
                {"FRANKLIN",144},
                {"FRAZIER",145},
                {"FREEMAN",146},
                {"FUENTES",147},
                {"FULLER",148},
                {"GALLAGHER",149},
                {"GALLEGOS",150},
                {"GARCIA",151},
                {"GARDNER",152},
                {"GARNER",153},
                {"GARRETT",154},
                {"GARZA",155},
                {"GEORGE",156},
                {"GIBSON",157},
                {"GILBERT",158},
                {"GILL",159},
                {"GOMEZ",160},
                {"GONZALES",161},
                {"GONZALEZ",162},
                {"GOODMAN",163},
                {"GOODWIN",164},
                {"GORDON",165},
                {"GRAHAM",166},
                {"GRANT",167},
                {"GRAVES",168},
                {"GRAY",169},
                {"GREEN",170},
                {"GREENE",171},
                {"GREGORY",172},
                {"GRIFFIN",173},
                {"GRIFFITH",174},
                {"GROSS",175},
                {"GUERRA",176},
                {"GUERRERO",177},
                {"GUTIERREZ",178},
                {"GUZMAN",179},
                {"HAIL",180},
                {"HALE",181},
                {"HALL",182},
                {"HAMILTON",183},
                {"HAMMOND",184},
                {"HAMPTON",185},
                {"HANSEN",186},
                {"HANSON",187},
                {"HARDY",188},
                {"HARMON",189},
                {"HARPER",190},
                {"HARRINGTON",191},
                {"HARRIS",192},
                {"HARRISON",193},
                {"HART",194},
                {"HARVEY",195},
                {"HAWKINS",196},
                {"HAYES",197},
                {"HAYNES",198},
                {"HENDERSON",199},
                {"HENRY",200},
                {"HERNANDEZ",201},
                {"HERRERA",202},
                {"HICKS",203},
                {"HIGGINS",204},
                {"HILL",205},
                {"HINES",206},
                {"HODGES",207},
                {"HOFFMAN",208},
                {"HOLLAND",209},
                {"HOLMES",210},
                {"HOLT",211},
                {"HOPKINS",212},
                {"HORTON",213},
                {"HOWARD",214},
                {"HOWELL",215},
                {"HUANG",216},
                {"HUBBARD",217},
                {"HUDSON",218},
                {"HUGHES",219},
                {"HUNT",220},
                {"HUNTER",221},
                {"INGRAM",222},
                {"JACKSON",223},
                {"JACOBS",224},
                {"JAMES",225},
                {"JENKINS",226},
                {"JENNINGS",227},
                {"JENSEN",228},
                {"JIMENEZ",229},
                {"JOHNSON",230},
                {"JOHNSTON",231},
                {"JONES",232},
                {"JORDAN",233},
                {"JOSEPH",234},
                {"JUAREZ",235},
                {"KELLER",236},
                {"KELLEY",237},
                {"KELLY",238},
                {"KENNEDY",239},
                {"KHAN",240},
                {"KIM",241},
                {"KING",242},
                {"KLEIN",243},
                {"KNIGHT",244},
                {"LAMBERT",245},
                {"LANE",246},
                {"LARA",247},
                {"LARSON",248},
                {"LAWRENCE",249},
                {"LAWSON",250},
                {"LE",251},
                {"LEE",252},
                {"LEON",253},
                {"LEONARD",254},
                {"LEWIS",255},
                {"LI",256},
                {"LIN",257},
                {"LITTLE",258},
                {"LIU",259},
                {"LOGAN",260},
                {"LONG",261},
                {"LOPEZ",262},
                {"LOVE",263},
                {"LOWE",264},
                {"LUCAS",265},
                {"LUNA",266},
                {"LYNCH",267},
                {"LYONS",268},
                {"MACK",269},
                {"MALDONADO",270},
                {"MALONE",271},
                {"MANN",272},
                {"MANNING",273},
                {"MARQUEZ",274},
                {"MARSHALL",275},
                {"MARTIN",276},
                {"MARTINEZ",277},
                {"MASON",278},
                {"MATTHEWS",279},
                {"MAXWELL",280},
                {"MAY",281},
                {"MCCARTHY",282},
                {"MCCOY",283},
                {"MCDANIEL",284},
                {"MCDONALD",285},
                {"MCGEE",286},
                {"MCKINNEY",287},
                {"MCLAUGHLIN",288},
                {"MEDINA",289},
                {"MEJIA",290},
                {"MENDEZ",291},
                {"MENDOZA",292},
                {"MEYER",293},
                {"MILES",294},
                {"MILLER",295},
                {"MILLS",296},
                {"MIRANDA",297},
                {"MITCHELL",298},
                {"MOLINA",299},
                {"MONTGOMERY",300},
                {"MONTOYA",301},
                {"MOORE",302},
                {"MORALES",303},
                {"MORAN",304},
                {"MORENO",305},
                {"MORGAN",306},
                {"MORRIS",307},
                {"MORRISON",308},
                {"MOSS",309},
                {"MULLINS",310},
                {"MUNOZ",311},
                {"MURPHY",312},
                {"MURRAY",313},
                {"MYERS",314},
                {"NAVARRO",315},
                {"NEAL",316},
                {"NELSON",317},
                {"NEWMAN",318},
                {"NEWTON",319},
                {"NGUYEN",320},
                {"NICHOLS",321},
                {"NORMAN",322},
                {"NORRIS",323},
                {"NUNEZ",324},
                {"OBRIEN",325},
                {"OCHOA",326},
                {"OCONNOR",327},
                {"OLIVER",328},
                {"OLSON",329},
                {"ORTEGA",330},
                {"ORTIZ",331},
                {"OWENS",332},
                {"PACHECO",333},
                {"PADILLA",334},
                {"PAGE",335},
                {"PALMER",336},
                {"PARK",337},
                {"PARKER",338},
                {"PARKS",339},
                {"PARSONS",340},
                {"PATEL",341},
                {"PATTERSON",342},
                {"PAUL",343},
                {"PAYNE",344},
                {"PEARSON",345},
                {"PENA",346},
                {"PEREZ",347},
                {"PERKINS",348},
                {"PERRY",349},
                {"PERSON",350},
                {"PETERS",351},
                {"PETERSON",352},
                {"PHAM",353},
                {"PHILLIPS",354},
                {"PIERCE",355},
                {"PORTER",356},
                {"POTTER",357},
                {"POWELL",358},
                {"POWERS",359},
                {"PRICE",360},
                {"QUINN",361},
                {"RAMIREZ",362},
                {"RAMOS",363},
                {"RAMSEY",364},
                {"RAY",365},
                {"REED",366},
                {"REESE",367},
                {"REEVES",368},
                {"REID",369},
                {"REYES",370},
                {"REYNOLDS",371},
                {"RHODES",372},
                {"RICE",373},
                {"RICHARDS",374},
                {"RICHARDSON",375},
                {"RILEY",376},
                {"RIOS",377},
                {"RIVAS",378},
                {"RIVERA",379},
                {"ROBBINS",380},
                {"ROBERTS",381},
                {"ROBERTSON",382},
                {"ROBINSON",383},
                {"ROBLES",384},
                {"RODGERS",385},
                {"RODRIGUEZ",386},
                {"ROGERS",387},
                {"ROJAS",388},
                {"ROMAN",389},
                {"ROMERO",390},
                {"ROSALES",391},
                {"ROSE",392},
                {"ROSS",393},
                {"ROWE",394},
                {"RUIZ",395},
                {"RUSSELL",396},
                {"RYAN",397},
                {"SALAZAR",398},
                {"SALINAS",399},
                {"SANCHEZ",400},
                {"SANDERS",401},
                {"SANDOVAL",402},
                {"SANTIAGO",403},
                {"SANTOS",404},
                {"SAUNDERS",405},
                {"SCHMIDT",406},
                {"SCHNEIDER",407},
                {"SCHROEDER",408},
                {"SCHULTZ",409},
                {"SCHWARTZ",410},
                {"SCOTT",411},
                {"SERRANO",412},
                {"SHARP",413},
                {"SHAW",414},
                {"SHELTON",415},
                {"SHERMAN",416},
                {"SILVA",417},
                {"SIMMONS",418},
                {"SIMON",419},
                {"SIMPSON",420},
                {"SIMS",421},
                {"SINGH",422},
                {"SMITH",423},
                {"SNYDER",424},
                {"SOLIS",425},
                {"SOTO",426},
                {"SPENCER",427},
                {"STANLEY",428},
                {"STEELE",429},
                {"STEPHENS",430},
                {"STEVENS",431},
                {"STEVENSON",432},
                {"STEWART",433},
                {"STONE",434},
                {"STRICKLAND",435},
                {"SULLIVAN",436},
                {"SUTTON",437},
                {"SWANSON",438},
                {"TATE",439},
                {"TAYLOR",440},
                {"TERRY",441},
                {"THOMAS",442},
                {"THOMPSON",443},
                {"THORNTON",444},
                {"TODD",445},
                {"TORRES",446},
                {"TOWNSEND",447},
                {"TRAN",448},
                {"TRUJILLO",449},
                {"TUCKER",450},
                {"TURNER",451},
                {"VALDEZ",452},
                {"VALENCIA",453},
                {"VARGAS",454},
                {"VASQUEZ",455},
                {"VAUGHN",456},
                {"VAZQUEZ",457},
                {"VEGA",458},
                {"VELASQUEZ",459},
                {"WADE",460},
                {"WAGNER",461},
                {"WALKER",462},
                {"WALLACE",463},
                {"WALSH",464},
                {"WALTERS",465},
                {"WALTON",466},
                {"WANG",467},
                {"WARD",468},
                {"WARNER",469},
                {"WARREN",470},
                {"WASHINGTON",471},
                {"WATERS",472},
                {"WATKINS",473},
                {"WATSON",474},
                {"WATTS",475},
                {"WEAVER",476},
                {"WEBB",477},
                {"WEBER",478},
                {"WEBSTER",479},
                {"WELCH",480},
                {"WELLS",481},
                {"WEST",482},
                {"WHEELER",483},
                {"WHITE",484},
                {"WILLIAMS",485},
                {"WILLIAMSON",486},
                {"WILLIS",487},
                {"WILSON",488},
                {"WISE",489},
                {"WOLF",490},
                {"WOLFE",491},
                {"WONG",492},
                {"WOOD",493},
                {"WOODS",494},
                {"WRIGHT",495},
                {"WU",496},
                {"YANG",497},
                {"YOUNG",498},
                {"ZHANG",499},
                {"ZIMMERMAN",500}
        };

unordered_map<string, int> first_names =
        {
                {"AALIYAH",1},
                {"AARON",2},
                {"ABEL",3},
                {"ABIGAIL",4},
                {"ABRAHAM",5},
                {"ADALINE",6},
                {"ADALYN",7},
                {"ADALYNN",8},
                {"ADAM",9},
                {"ADDISON",10},
                {"ADELINE",11},
                {"ADELYN",12},
                {"ADRIAN",13},
                {"ADRIANA",14},
                {"AIDAN",15},
                {"AIDEN",16},
                {"ALAINA",17},
                {"ALAN",18},
                {"ALANA",19},
                {"ALAYNA",20},
                {"ALEJANDRO",21},
                {"ALEX",22},
                {"ALEXA",23},
                {"ALEXANDER",24},
                {"ALEXANDRA",25},
                {"ALEXIS",26},
                {"ALICE",27},
                {"ALINA",28},
                {"ALIVIA",29},
                {"ALIYAH",30},
                {"ALLISON",31},
                {"ALYSSA",32},
                {"AMARA",33},
                {"AMAYA",34},
                {"AMELIA",35},
                {"AMIR",36},
                {"AMY",37},
                {"ANA",38},
                {"ANASTASIA",39},
                {"ANDREA",40},
                {"ANDRES",41},
                {"ANDREW",42},
                {"ANGEL",43},
                {"ANGELA",44},
                {"ANGELINA",45},
                {"ANNA",46},
                {"ANNABELLE",47},
                {"ANTHONY",48},
                {"ANTONIO",49},
                {"ARABELLA",50},
                {"ARIA",51},
                {"ARIANA",52},
                {"ARIANNA",53},
                {"ARIEL",54},
                {"ARTHUR",55},
                {"ARYA",56},
                {"ASHER",57},
                {"ASHLEY",58},
                {"ASHTON",59},
                {"ATHENA",60},
                {"AUBREE",61},
                {"AUBREY",62},
                {"AUDREY",63},
                {"AUGUST",64},
                {"AURORA",65},
                {"AUSTIN",66},
                {"AUTUMN",67},
                {"AVA",68},
                {"AVERY",69},
                {"AVERY",70},
                {"AXEL",71},
                {"AYDEN",72},
                {"AYLA",73},
                {"BAILEY",74},
                {"BARRETT",75},
                {"BEAU",76},
                {"BECKETT",77},
                {"BELLA",78},
                {"BENJAMIN",79},
                {"BENNETT",80},
                {"BENTLEY",81},
                {"BLAKE",82},
                {"BRADLEY",83},
                {"BRADY",84},
                {"BRANDON",85},
                {"BRANTLEY",86},
                {"BRAXTON",87},
                {"BRAYDEN",88},
                {"BRIAN",89},
                {"BRIANNA",90},
                {"BRIELLE",91},
                {"BRODY",92},
                {"BROOKE",93},
                {"BROOKLYN",94},
                {"BROOKLYNN",95},
                {"BROOKS",96},
                {"BRYAN",97},
                {"BRYCE",98},
                {"BRYNLEE",99},
                {"BRYSON",100},
                {"CADEN",101},
                {"CALEB",102},
                {"CALLIE",103},
                {"CALVIN",104},
                {"CAMDEN",105},
                {"CAMERON",106},
                {"CAMILA",107},
                {"CARLOS",108},
                {"CAROLINE",109},
                {"CARSON",110},
                {"CARTER",111},
                {"CATHERINE",112},
                {"CAYDEN",113},
                {"CECILIA",114},
                {"CHARLES",115},
                {"CHARLIE",116},
                {"CHARLIE",117},
                {"CHARLOTTE",118},
                {"CHASE",119},
                {"CHLOE",120},
                {"CHRISTIAN",121},
                {"CHRISTOPHER",122},
                {"CLAIRE",123},
                {"CLARA",124},
                {"CLAYTON",125},
                {"COLE",126},
                {"COLIN",127},
                {"COLTON",128},
                {"CONNOR",129},
                {"COOPER",130},
                {"CORA",131},
                {"DAISY",132},
                {"DAKOTA",133},
                {"DALEYZA",134},
                {"DAMIAN",135},
                {"DANIEL",136},
                {"DANIELA",137},
                {"DAVID",138},
                {"DAWSON",139},
                {"DEAN",140},
                {"DECLAN",141},
                {"DELANEY",142},
                {"DELILAH",143},
                {"DEREK",144},
                {"DESTINY",145},
                {"DIANA",146},
                {"DIEGO",147},
                {"DOMINIC",148},
                {"DYLAN",149},
                {"EASTON",150},
                {"EDEN",151},
                {"EDWARD",152},
                {"ELEANOR",153},
                {"ELENA",154},
                {"ELI",155},
                {"ELIANA",156},
                {"ELIAS",157},
                {"ELIJAH",158},
                {"ELISE",159},
                {"ELIZA",160},
                {"ELIZABETH",161},
                {"ELLA",162},
                {"ELLIANA",163},
                {"ELLIE",164},
                {"ELLIOT",165},
                {"ELLIOTT",166},
                {"ELOISE",167},
                {"EMERSON",168},
                {"EMERSYN",169},
                {"EMERY",170},
                {"EMILIA",171},
                {"EMILIANO",172},
                {"EMILY",173},
                {"EMMA",174},
                {"EMMANUEL",175},
                {"EMMETT",176},
                {"ERIC",177},
                {"ESTHER",178},
                {"ETHAN",179},
                {"EVA",180},
                {"EVAN",181},
                {"EVELYN",182},
                {"EVERETT",183},
                {"EVERLY",184},
                {"EZEKIEL",185},
                {"EZRA",186},
                {"FAITH",187},
                {"FELIX",188},
                {"FINLEY",189},
                {"FINN",190},
                {"FIONA",191},
                {"GABRIEL",192},
                {"GABRIELLA",193},
                {"GAEL",194},
                {"GAVIN",195},
                {"GENESIS",196},
                {"GENEVIEVE",197},
                {"GEORGE",198},
                {"GEORGIA",199},
                {"GIANNA",200},
                {"GIOVANNI",201},
                {"GRACE",202},
                {"GRACIE",203},
                {"GRAHAM",204},
                {"GRANT",205},
                {"GRAYSON",206},
                {"GREYSON",207},
                {"GRIFFIN",208},
                {"HADLEY",209},
                {"HAILEY",210},
                {"HANNAH",211},
                {"HARLEY",212},
                {"HARMONY",213},
                {"HARPER",214},
                {"HARRISON",215},
                {"HAYDEN",216},
                {"HAYDEN",217},
                {"HAZEL",218},
                {"HENRY",219},
                {"HOLDEN",220},
                {"HUDSON",221},
                {"HUNTER",222},
                {"IAN",223},
                {"IRIS",224},
                {"ISAAC",225},
                {"ISABEL",226},
                {"ISABELLA",227},
                {"ISABELLE",228},
                {"ISAIAH",229},
                {"ISLA",230},
                {"ISRAEL",231},
                {"IVAN",232},
                {"IVY",233},
                {"JACE",234},
                {"JACK",235},
                {"JACKSON",236},
                {"JACOB",237},
                {"JADE",238},
                {"JADEN",239},
                {"JAKE",240},
                {"JAMES",241},
                {"JAMESON",242},
                {"JASMINE",243},
                {"JASON",244},
                {"JASPER",245},
                {"JAVIER",246},
                {"JAX",247},
                {"JAXON",248},
                {"JAXSON",249},
                {"JAYCE",250},
                {"JAYDEN",251},
                {"JAYLA",252},
                {"JEREMIAH",253},
                {"JEREMY",254},
                {"JESSE",255},
                {"JESSICA",256},
                {"JESUS",257},
                {"JOANNA",258},
                {"JOCELYN",259},
                {"JOEL",260},
                {"JOHN",261},
                {"JONAH",262},
                {"JONATHAN",263},
                {"JORDAN",264},
                {"JORDYN",265},
                {"JORGE",266},
                {"JOSE",267},
                {"JOSEPH",268},
                {"JOSEPHINE",269},
                {"JOSHUA",270},
                {"JOSIAH",271},
                {"JOSIE",272},
                {"JOSUE",273},
                {"JUAN",274},
                {"JUDAH",275},
                {"JUDE",276},
                {"JULIA",277},
                {"JULIAN",278},
                {"JULIANA",279},
                {"JULIANNA",280},
                {"JULIET",281},
                {"JULIETTE",282},
                {"JUNE",283},
                {"JUSTIN",284},
                {"KADEN",285},
                {"KAI",286},
                {"KAIDEN",287},
                {"KALEB",288},
                {"KARTER",289},
                {"KATHERINE",290},
                {"KAYDEN",291},
                {"KAYLA",292},
                {"KAYLEE",293},
                {"KENDALL",294},
                {"KENNEDY",295},
                {"KENNETH",296},
                {"KEVIN",297},
                {"KHLOE",298},
                {"KILLIAN",299},
                {"KIMBERLY",300},
                {"KING",301},
                {"KINGSTON",302},
                {"KINSLEY",303},
                {"KNOX",304},
                {"KYLE",305},
                {"KYLIE",306},
                {"KYRIE",307},
                {"LAILA",308},
                {"LANDON",309},
                {"LAUREN",310},
                {"LAYLA",311},
                {"LEAH",312},
                {"LEILA",313},
                {"LEILANI",314},
                {"LEO",315},
                {"LEON",316},
                {"LEONARDO",317},
                {"LEVI",318},
                {"LIAM",319},
                {"LILA",320},
                {"LILIANA",321},
                {"LILLIAN",322},
                {"LILLY",323},
                {"LILY",324},
                {"LINCOLN",325},
                {"LOGAN",326},
                {"LOLA",327},
                {"LONDON",328},
                {"LONDYN",329},
                {"LORENZO",330},
                {"LUCA",331},
                {"LUCAS",332},
                {"LUCIA",333},
                {"LUCY",334},
                {"LUIS",335},
                {"LUKAS",336},
                {"LUKE",337},
                {"LUNA",338},
                {"LYDIA",339},
                {"LYLA",340},
                {"MACKENZIE",341},
                {"MADDOX",342},
                {"MADELINE",343},
                {"MADELYN",344},
                {"MADISON",345},
                {"MAGGIE",346},
                {"MAKAYLA",347},
                {"MALACHI",348},
                {"MALIA",349},
                {"MARCUS",350},
                {"MARGARET",351},
                {"MARIA",352},
                {"MARIAH",353},
                {"MARK",354},
                {"MARLEY",355},
                {"MARY",356},
                {"MASON",357},
                {"MATEO",358},
                {"MATIAS",359},
                {"MATTEO",360},
                {"MATTHEW",361},
                {"MAVERICK",362},
                {"MAX",363},
                {"MAXIMUS",364},
                {"MAXWELL",365},
                {"MAYA",366},
                {"MCKENZIE",367},
                {"MELANIE",368},
                {"MELODY",369},
                {"MESSIAH",370},
                {"MIA",371},
                {"MICAH",372},
                {"MICHAEL",373},
                {"MICHELLE",374},
                {"MIGUEL",375},
                {"MILA",376},
                {"MILES",377},
                {"MILO",378},
                {"MOLLY",379},
                {"MORGAN",380},
                {"MYA",381},
                {"MYLES",382},
                {"NAOMI",383},
                {"NATALIA",384},
                {"NATALIE",385},
                {"NATHAN",386},
                {"NATHANIEL",387},
                {"NEVAEH",388},
                {"NICHOLAS",389},
                {"NICOLAS",390},
                {"NICOLE",391},
                {"NOAH",392},
                {"NOELLE",393},
                {"NOLAN",394},
                {"NORA",395},
                {"NORAH",396},
                {"NOVA",397},
                {"OLIVER",398},
                {"OLIVIA",399},
                {"OMAR",400},
                {"OSCAR",401},
                {"OWEN",402},
                {"PAIGE",403},
                {"PAISLEY",404},
                {"PARKER",405},
                {"PARKER",406},
                {"PATRICK",407},
                {"PAUL",408},
                {"PAXTON",409},
                {"PAYTON",410},
                {"PENELOPE",411},
                {"PETER",412},
                {"PEYTON",413},
                {"PIPER",414},
                {"PRESLEY",415},
                {"PRESTON",416},
                {"QUINN",417},
                {"RACHEL",418},
                {"RAELYNN",419},
                {"REAGAN",420},
                {"REBECCA",421},
                {"REESE",422},
                {"REMI",423},
                {"REMINGTON",424},
                {"RHETT",425},
                {"RICHARD",426},
                {"RILEY",427},
                {"RIVER",428},
                {"ROBERT",429},
                {"ROMAN",430},
                {"ROSALIE",431},
                {"ROSE",432},
                {"ROWAN",433},
                {"ROWAN",434},
                {"RUBY",435},
                {"RYAN",436},
                {"RYDER",437},
                {"RYKER",438},
                {"RYLEE",439},
                {"RYLEIGH",440},
                {"SADIE",441},
                {"SAMANTHA",442},
                {"SAMUEL",443},
                {"SANTIAGO",444},
                {"SARA",445},
                {"SARAH",446},
                {"SAVANNAH",447},
                {"SAWYER",448},
                {"SAWYER",449},
                {"SCARLETT",450},
                {"SEBASTIAN",451},
                {"SELENA",452},
                {"SERENITY",453},
                {"SIENNA",454},
                {"SILAS",455},
                {"SKYLAR",456},
                {"SLOANE",457},
                {"SOFIA",458},
                {"SOPHIA",459},
                {"SOPHIE",460},
                {"STELLA",461},
                {"STEVEN",462},
                {"SUMMER",463},
                {"SYDNEY",464},
                {"TAYLOR",465},
                {"TEAGAN",466},
                {"TESSA",467},
                {"THEODORE",468},
                {"THIAGO",469},
                {"THOMAS",470},
                {"TIMOTHY",471},
                {"TRINITY",472},
                {"TRISTAN",473},
                {"TUCKER",474},
                {"TYLER",475},
                {"VALENTINA",476},
                {"VALERIA",477},
                {"VALERIE",478},
                {"VANESSA",479},
                {"VICTOR",480},
                {"VICTORIA",481},
                {"VINCENT",482},
                {"VIOLET",483},
                {"VIVIAN",484},
                {"WAYLON",485},
                {"WESLEY",486},
                {"WESTON",487},
                {"WILLIAM",488},
                {"WILLOW",489},
                {"WYATT",490},
                {"XANDER",491},
                {"XAVIER",492},
                {"XIMENA",493},
                {"ZACHARY",494},
                {"ZANDER",495},
                {"ZANE",496},
                {"ZAYDEN",497},
                {"ZION",498},
                {"ZOE",499},
                {"ZOEY",500}
        };

struct individual //contains last and first name index number + pointer
{
    int last;
    int first;
    int ssn;
    Data* profile; // direct connection to list
};

list<individual *> list1; //list used to compare profiles

bool mycompare_full(individual *a, individual *b) //compares last, first, and ssn
{
    if (b->last!=a->last)
    {
        return b->last>a->last;
    }
    else if (b->first!=a->first)
    {
        return b->first>a->first;
    }
    else if (b->ssn!=a->ssn)
    {
        return b->ssn > a->ssn;
    }
}

bool mycompare_ssn(individual *a, individual *b) //compares only ssn (T4)
{
    if (b->ssn!=a->ssn)
    {
        return b->ssn > a->ssn;
    }
}

int convert_ssn_to_int(string ssn) //converts ssn to int and takes out '-'
{
    ssn.erase(remove(ssn.begin(),ssn.end(),'-'),ssn.end());
    int a=stoi(ssn);
    return a;
}


void sortDataList(list<Data *> &l) {
    // Fill this in


    if (l.size() <1000000) //if sample = T1
    {
        for (auto person: l)
        {
            list1.push_back(new individual{last_names[person->lastName],first_names[person->firstName], convert_ssn_to_int(person->ssn),  person});
        }
        list1.sort(mycompare_full);
        l.clear();

        for (auto individual: list1)
        {
            l.push_back(individual->profile);
        }
    }
    else if ((l.front()->firstName == l.back()->firstName)&&(l.front()->lastName == l.back()->lastName)) //T4 (only numbers) - dependent on low probability
    {
        for (auto person: l)
        {
            list1.push_back(new individual{0,0, convert_ssn_to_int(person->ssn),  person}); // only needs to compare ssn values
        }
        list1.sort(mycompare_ssn);
        l.clear();

        for (auto individual: list1)
        {
            l.push_back(individual->profile);
        }
    }
    else //T2 or T3
    {

        auto it = l.begin(); // iterator for list

        if ((l.front()->firstName < (*it++)->firstName) && (l.front()->lastName < (*it++)->lastName) && (l.front()->ssn < (*it++)->ssn)) //T3 - dependent on low probablity
        {
            for (auto person: l)
            {
                list1.push_back(new individual{0,0, convert_ssn_to_int(person->ssn),  person}); // only needs to compare ssn values
            }
            list1.sort(mycompare_ssn);
            l.clear();

            for (auto individual: list1)
            {
                l.push_back(individual->profile);
            }
        }
        else //T2
        {
            for (auto person: l)
            {
                list1.push_back(new individual{last_names[person->lastName],first_names[person->firstName], convert_ssn_to_int(person->ssn),  person});
            }
            list1.sort(mycompare_full);
            l.clear();

            for (auto individual: list1)
            {
                l.push_back(individual->profile);
            }
        }

    }
};

